### ISSUE TITLE
No explanation regarding the security of the SN credentials

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#10]
Currently, the add-on is missing a detailed explanation where and how the SN credentials are being used and saved. I am thinking of Firefox/Google Sync, Multi-User-Systems and so on.

**Comment by johnjones4** [comment]
How's this for a message:

> Your encrypted login credentials and 2FA code (when applicable) are sent directly to the Standard Notes server at sync.standardnotes.org and never stored locally on this machine. This add-on only stores the authentication token data sent back from the server to make future requests. This add-on also does not store any note data - only editor and tag data.

**Comment by jrabensc** [comment]
Sounds good to me.
