### ISSUE TITLE
New clipping methods

### ISSUE THREAD

**Issue by ghost** [johnjones4/Standard-Notes-Clipper#13]
Are there plans to support the following clipping modes in the future?

- URL (name: page title / body: hyperlink to page + featured image)
- Simplified article (like Joplin has; the body text (auto-detects what should be the main content) in Markdown)

Thanks in advance for your reply!

**Comment by rafikiphoto** [comment]
I'd like to see the same options as in Joplin and Evernote webclipper:
Article
Simplified article
Screenshot
Full page
Bookmark (url)

**Comment by johnjones4** [comment]
So I've added an "Article" and "Bookmark" options for the next version. Screenshot is a bit difficult because of how attachments are handled in Standard Notes. 

@rafikiphoto can you expand on what you mean for "Simplified article" and "Full page"?

**Comment by johnjones4** [comment]
You can try it now: https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.4.0

**Comment by ghost** [comment]
It works! Currently, I use the bold editor to save articles as any other note format takes the HTML with it and it looks odd. Are there plans to implement the Joplin-style simplified article i.e. the same as it is right now but preformatted?

Also, it would be a great idea to have a 'source' link at the bottom of article, highlight and area clips to know on which URL the clipped text was found.

What do you think of the two above ideas?

**Comment by johnjones4** [comment]
#15 # #

**Comment by johnjones4** [comment]
I've opened #15 to add source URL and I'm also going to implement a new feature related to this to modify the formatting of the clipped content based on their preferred editor (#16). I'll also address the Joplin-style simplification feature under this ticket.

**Comment by johnjones4** [comment]
I've now implemented HTML cleanup for the "Article" mode. @Kazer999 can you test it out here https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.5.0 ?

**Comment by ghost** [comment]
Amazing. Thank you so much for your efforts in making SN user's life easier. This ticket can be closed afaic.

**Comment by ghost** [comment]
Hi @johnjones4, seems like I posted without seeing your comment. The HTML is definitely cleaner and less intrusive now, but using the bold editor will no longer clip the picture(s) of an article (whereas it used to do that in the past).

I tested 1.4 and 1.5 on [this article](https://www.standaard.be/cnt/dmf20191203_04748563) and the latest version doesn't clip the image.

**Comment by johnjones4** [comment]
It appears the HTML scrubbing module I've used doesn't allow img tags by default. I've corrected this for the next release. Do you think it would make sense to offer control of the HTML tags whitelist in settings?

**Comment by johnjones4** [comment]
https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.5.1

**Comment by ghost** [comment]
Tested and this works great now. As for your whitelisting suggestion: I personally wouldn't do it, keeping the SN ethos of simplicity in mind. This adds complexity for the user, assuming some of them won't know what it's for. Adding <img> to the whitelist made sense as other clippers from competing products do the same thing, and they don't provide the option to 'leave out images when clipping' - something I've never read a single complaint about. Keeping that in mind, I would leave it as it is right now - my 2 cents.

**Comment by johnjones4** [comment]
Makes sense! I definitely don't want to overthink the features on this project and then end up supporting things no one cares about. Thanks!
