### ISSUE TITLE
Choose editor when clipping, not via options

### ISSUE THREAD

**Issue by ghost** [johnjones4/Standard-Notes-Clipper#17]
It's somewhat counter-intuitive to change your preferred editor somewhere deep down in the extension settings. I see the case for choosing your editor when performing the clip (as different content needs different editors).

Of course, you can still change it easily on the note but it may lead to weird results (e.g. HTML formatting in a markdown note etc., although there's #16 open for that already).

Just a minor issue.

**Comment by johnjones4** [comment]
I think this is a great idea. What I might do is implement it so that there is a "preferred editor" setting for each clipping mode, which is editable in preferences, and then that option also appears and can be updated on each clip. @Kazer999, do you think that if a user changes the editor during clipping, then it should update the preferred editor setting for that mode?

**Comment by ghost** [comment]
- Preferred editor per clipping mode: great idea, this makes total sense although it adds complexity for the user.
- Editor option appear during clipping: also a great idea (and my original suggestion) :-)
- Update preferred editor for that mode when changing it on a single clip: wouldn't do this, as this would mean that 'one-offs' mean having to change the editor the next time. This would make the preferred editor option nothing more than a 'remember last editor used for that mode', right? Making the idea of the preferred editor invalid. E.g. I highlight code that I see somewhere, right click and change to code editor. Next time I'll select something else, but am met with my selection being stored in the code editor; which I didn't want, because I specifically set the preferred editor of highlighted text to for example bold editor. (Hope my explanation makes sense; I just think that this AND a preferred editor are mutually exclusive)

**Comment by johnjones4** [comment]
Available for testing! https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.6.0
