### ISSUE TITLE
Tags misinterpret spaces

### ISSUE THREAD

**Issue by ghost** [johnjones4/Standard-Notes-Clipper#18]
I sort my notebooks with a "[number] " in front, e.g.

* [2] Personal
    * Music
    * Articles
* [3] Work
    * Leave

etc.

The web clipper misinterprets these spaces as new tags. For example, in the picture attached it will regard the tag

`[2] Persoonlijk.Muziek`

as two separate tags, namely

`[2]` and `Persoonlijk.Muziek`

![Capture](https://user-images.githubusercontent.com/14114150/70030599-d8d95700-15a9-11ea-89e9-6e08a3ae36d5.PNG)

**Comment by johnjones4** [comment]
Available for testing: https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.5.2

**Comment by ghost** [comment]
Much better! Doing a great job, John!

Another suggestion: show up the tags that correspond to a string that you type instead of having to type the tag in its entirety, starting from the first character.

**EXAMPLE**

Now: when I type 'muz' I don't get suggested tags. When I start typing '[2' I get the suggestion for '[2] Persoonlijk.muziek' and all other tags that start with those characters.
Ideal: when I type 'muz', all tags that have the string 'muz' in it are shown (such as '[2] Persoonlijk.muziek' in this case, but perhaps also others)

What do you think? I believe it makes sense and makes you work faster, thus increasing productivity.

**Comment by johnjones4** [comment]
So you'd like the tag search to suggest based on a general string search and not a "starts with" search as it does now? My concern with that is I don't think that's how SN's tag search function behaves.

**Comment by ghost** [comment]
Ideally yes, if that's possible. I believe that that is the most user-friendly way of adding tags.

I noticed that searching for tags within SN itself behaves as follows: it is a ''starts with'' search but that 'start' applies to subtags as well. For example, typing ''a'' will bring up the ''#[2] Persoonlijk.Artikels'' tag, whereas the clipper will only bring that up when typing ''[''.

**Comment by johnjones4** [comment]
I see now - I haven't been using subtags but I see how SN handles them now and why it creates this behavior. Stay tuned for a fix this week.

**Comment by johnjones4** [comment]
Sorry for the delay - I think we have this now. Stay tuned for the next build

**Comment by johnjones4** [comment]
https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.6.1
