### ISSUE TITLE
Images duplicated after clipping

### ISSUE THREAD

**Issue by georgecher** [johnjones4/Standard-Notes-Clipper#21]
Hello, clipping [this](https://resources.intenseschool.com/ospf-network-types/) page results in almost all images being duplicated in the clip.

![image](https://user-images.githubusercontent.com/12417320/71387483-01260580-25ec-11ea-8f12-9aade7164403.png)

**Comment by dannysummerlin** [comment]
Thanks for the heads up. Huh, that's interesting - so, they have an img tag and then a noscript tag with the same img tag inside it. That's pretty unusual, I could make the selector avoid noscript tags, but that might mess up other pages. For now I think I'll leave it more open, but let me know if you notice that on other websites

**Comment by johnjones4** [comment]
I'm not sure we can avoid this issue - it's very odd that the site hid an additional `img` in a `noscript` right?

**Comment by georgecher** [comment]
Yep, that is odd. I suppose you could have the extension check for this sort of thing, but it's probably not worth it just for one site.

Should I close the issue?

**Comment by johnjones4** [comment]
Yes we can close! Thanks!
