### ISSUE TITLE
Can not use it anymore

### ISSUE THREAD

**Issue by JadeVane** [johnjones4/Standard-Notes-Clipper#22]
I installed clipper two days before, and it works well. But it doesn't work today, and i get some error message from chrome, any idea about that?
![image](https://user-images.githubusercontent.com/34258753/71394780-074cce00-264e-11ea-867c-7277cb4d462e.png)

**Comment by johnjones4** [comment]
Are you following the install instructions on https://github.com/johnjones4/Standard-Notes-Clipper#installation? They've changed since I first released this.

**Comment by JadeVane** [comment]
Of course, step by step, and I have the best experience just two day before. BTW,  I have tried reinstalling it several times after the error message appeared, doesn't seem to work.

**Comment by johnjones4** [comment]
Totally weird. What Chrome version are you on?

**Comment by JadeVane** [comment]
Some infomation that may be useful here:
- chrome version: 79.0.3945.79 (64-bit version)
- system version: Ubuntu 19.10
- kernel version: 5.3.0-24

**Comment by johnjones4** [comment]
@JadeVane Haven't forgotten you here. Could you do me a favor and try out the addon with Firefox on Ubuntu?

**Comment by JadeVane** [comment]
After experimenting, I found that this error can be reproduced after changing the default editor in the settings interface. At the same time, a note `missing key` will appear in the notebook list after clipping, and deleting this note will also reproduce this error.

**Comment by johnjones4** [comment]
Thanks for digging-into this issue. Would you mind doing a screen recording of the issue?

**Comment by JadeVane** [comment]
After changing the default editor, the editor list in settings interface just keep loading, and I will get the error `Unexpected number in JSON...` show in a pop-up prompt when I push the cilpper button.

The note name `missing key` appears in the notes list without any error message, just looks like this:

![image](https://user-images.githubusercontent.com/34258753/71703499-cacc5f80-2e0f-11ea-8db5-853c159b82e4.png)

and it shows something like this:

![image](https://user-images.githubusercontent.com/34258753/71703506-d586f480-2e0f-11ea-8afc-90d660b85e1d.png)

You can use it normally if you keep this note in the notes list.

**Comment by johnjones4** [comment]
Hi @JadeVane unfortunately I'm still unable to recreate this, but I'm going to keep an eye out for future reports experiencing a similar issue as I could be missing something. Until then, I am going to close this. Thanks for submitting the bug and I apologize that I'm unable to directly address it.
