### ISSUE TITLE
Option to choose different editor

### ISSUE THREAD

**Issue by dogskool** [johnjones4/Standard-Notes-Clipper#25]
When I clip from a web page, I have the choice to choose a different editor, but only the 'Plain Editor' is visible. Is there a way to get my other choices? (in both Firefox and Chrome)

**Comment by johnjones4** [comment]
Hi @dogskool. Which other editors do you have enabled in your account?

**Comment by dogskool** [comment]
Plain Editor, Bold Editor, Code Editor, Markdown Basic, Markdown Math, Markdown Pro, Plus Editor, Task Editor and Vim Editor. Almost all of them. 
![Screen Shot 2020-10-25 at 9 01 50 AM](https://user-images.githubusercontent.com/1085258/97112307-cb84f980-16a0-11eb-830e-7bff69b6abf9.png)

**Comment by ackstorm23** [comment]
I have the same problem.  No editor choices when clipping.

**Comment by DonCorleone1988** [comment]
I can concur that this is happening to me as well. I have almost all of the editors installed and the only option I have is the plain editor when clipping.

**Comment by johnjones4** [comment]
Sorry for the delay here! The issue is fixed and will be in the next release. Stay tuned

**Comment by johnjones4** [comment]
I believe this has been resolved in https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.7.1. Can someone please confirm for me?

**Comment by JaspalSuri** [comment]
Hi @johnjones4,

Thanks for adding this feature! I was able to confirm that this worked in two tests with different editors.
