### ISSUE TITLE
Clipper and self hosted SN not possible?

### ISSUE THREAD

**Issue by MichiFr** [johnjones4/Standard-Notes-Clipper#26]
Hi,

I'm hosting SN as well as the extensions locally on my NAS, running inside a docker container. Standard Notes is reachable from external using a https URL and works perfectly well.

When keying in my credentials and my URL for authentication, the login page of SN clipper just says "not found", nothing else. Is this a known issue or better asked: does the clipper not work with self hosted SN?

Michael

**Comment by MichiFr** [comment]
Never mind! If I had onyl chosen the correct (sync) URL, I would have properly logged in ;-)

**Comment by johnjones4** [comment]
All good! Thank you
