### ISSUE TITLE
Cannot find existing tags, cannot find any other editor, and selected tags are not attached to notes.

### ISSUE THREAD

**Issue by ackstorm23** [johnjones4/Standard-Notes-Clipper#27]
I have app.standardnotes.org loaded in another window in firefox, fully loggedin.

EDIT:   It creates both the new tag and the note, but the note itself is not tagged.

It also does not think I can use any editor but the plain text, as the others are not listed.

I have tried both clipping parts of an article or the whole 'article'.  No difference in default.

SN 3.5.3
Firefox 8.2.0.2

**Comment by johnjones4** [comment]
Sorry for the delay here! I believe this has been resolved in https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.7.1. Can you please confirm for me?

**Comment by ackstorm23** [comment]
Confirmed Fixed! Thanks!
