### ISSUE TITLE
Clipped Content is shown in the preview in SN

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#5]
Just tried to clip some texts and the clipped content is shown in the preview pane in SN:
![image](https://user-images.githubusercontent.com/6616405/67968480-c3b68480-fc07-11e9-8edf-6f274dd4b68f.png)

**Comment by johnjones4** [comment]
@jrabensc thanks for reporting! I've updated the code to set preview_plain with plaintext recommended in the Slack conversation. Can you give it a try now?

**Comment by jrabensc** [comment]
@johnjones4 works perfectly, thanks.
