### ISSUE TITLE
Cannot close the Clipping Dialogue

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#6]
Using Firefox 70.0 x64, I cannot close the Clipping Dialogue once opened. It misses a close button:

![image](https://user-images.githubusercontent.com/6616405/67968693-23149480-fc08-11e9-9768-f0c3b51ce634.png)

**Comment by johnjones4** [comment]
Button added!

**Comment by jrabensc** [comment]
Works as expected, thank you.
