### ISSUE TITLE
Selecting prefered Editor in Settings not working

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#7]
The dropdown in the settings menu is currently empty and not working for me:
![image](https://user-images.githubusercontent.com/6616405/67969024-adf58f00-fc08-11e9-95ef-f1825fbcb1df.png)

**Comment by johnjones4** [comment]
@jrabensc Which editors do you have installed in Standard Notes?

**Comment by jrabensc** [comment]
@johnjones4 These are my installed editors:
![image](https://user-images.githubusercontent.com/6616405/68020356-7e916180-fc9e-11e9-8310-d3b810180fae.png)

**Comment by johnjones4** [comment]
Really odd. Can grab a screenshot of the inspector for this plugin? (To get to that, go to Tools > Add-ons, then select the gear dropdown and click Debug Add-Ons, and then finally in the box for Standard Notes Clipper, click Inspect.)

**Comment by jrabensc** [comment]
Here's a screenshot of the inspector tab:
![image](https://user-images.githubusercontent.com/6616405/68031520-1d788680-fcbc-11e9-95bc-b8d332c080c3.png)

I found some errors in the console tab and grabbed them too, maybe they are helpfull as well:
![image](https://user-images.githubusercontent.com/6616405/68031656-629cb880-fcbc-11e9-84d2-4da7ac181eaf.png)

**Comment by joshcsullivan** [comment]
Hi, I am using Brave (Chromium) and also having an issue with the preferred editor not loading. I am getting a JS error when it attempts to get the list of editors, I have Advanced Markdown Editor, Bold Editor, Code Editor, Minimal Markdown Editor, Plus Editor installed. 

I've confirmed the extension has permissions to read and change site data on all sites.

Here is the console and error in the extension which shows it's encountering an error at the uuid:

<img width="881" alt="Screen Shot 2019-11-02 at 6 54 48 AM" src="https://user-images.githubusercontent.com/5774100/68069971-25790a80-fd3e-11e9-96ab-c6ee31f09fe0.png">

**Comment by johnjones4** [comment]
@joshcsullivan @jrabensc thanks for all of this great detail. I just pushed a change that I think might address this. Can you update and test again for me? Thanks!

**Comment by jrabensc** [comment]
Its working: 
![image](https://user-images.githubusercontent.com/6616405/68071767-174ade80-fd7e-11e9-95c4-918cf12fc159.png)

However, it is not possible to select the plain editor. Is there a reason for that?

**Comment by johnjones4** [comment]
Good call! I've added Plain Editor as an option.

**Comment by johnjones4** [comment]
@joshcsullivan looking good for you too?

**Comment by joshcsullivan** [comment]
Sorry, weekend was very busy.

Anyways, I can now select the Plain editor, but no other editors appear in the dropdown:

![20191104-091425](https://user-images.githubusercontent.com/5774100/68127305-9c9bd380-fee3-11e9-947f-99b3579a4a56.png)

As you can see, I have more editors than the Plain editor:

![20191104-091345](https://user-images.githubusercontent.com/5774100/68127325-a8879580-fee3-11e9-866c-d641afcbd040.png)

**Comment by johnjones4** [comment]
Looks like Brave/Chromium have different rules with the storage system. I've switched the add-on to use local storage which seems to fix the issue. You will need to log in again give the change in storage.

**Comment by joshcsullivan** [comment]
It's working now, thank you!
