### ISSUE TITLE
Start the clipping process using right-click menu

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#8]
I would really like to be able to start the clipping process by using the on-page right-click menu.

A plus would be to make this optional using the settings menu.

**Comment by johnjones4** [comment]
This feature is now available for testing from the master branch and will be included in the next release!

**Comment by jrabensc** [comment]
I get an error message when testing the current master by loading the manifest.json file:
![image](https://user-images.githubusercontent.com/6616405/68528178-b11b0a00-02ef-11ea-812e-6462580ee6af.png)

**Comment by johnjones4** [comment]
@jrabensc I've transitioned the project to use a build system, so you can either follow the build instructions here: https://github.com/johnjones4/Standard-Notes-Clipper#building-and-running-from-source or you can download a release for testing once I build the next version.

**Comment by jrabensc** [comment]
I would prefer downloading the release. Once the right-click clipping is included, I will test it and provide you with feedback.

**Comment by johnjones4** [comment]
This is now available for testing in the latest release! https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.2.0

**Comment by jrabensc** [comment]
There is no entry for the clipper in my right click menu:
![image](https://user-images.githubusercontent.com/6616405/68602875-73f97800-04a7-11ea-81a5-ddf8aab59e15.png)

Edit: Never mind, its working. I just had to select some text before clicking. Great feature, thank you!
