### ISSUE TITLE
Quick tags functionality like in SN when entering tags

### ISSUE THREAD

**Issue by jrabensc** [johnjones4/Standard-Notes-Clipper#9]
It would be nice to have the same quick tags functionality as we already have in SN when entering the tags for a new clip.

**Comment by johnjones4** [comment]
This is now available for testing in the latest release! https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.2.0

**Comment by jrabensc** [comment]
Works as expected, thank you.
